[package]
name = "stract_admin"
version = "0.1.0"
description = "A Tauri App"
author = [
  "Andrii Shafar <andreyshafar@gmail.com>",
  "Orest Pidfihurnyi <orest988@gmail.com>"
]
license = "GPLv3"
repository = "https://gitlab.com/Reidond/stract"
default-run = "stract_admin"
edition = "2018"
build = "src/build.rs"

[package.metadata.bundle]
identifier = "com.tauri.dev"
icon = [
  "icons/32x32.png",
  "icons/128x128.png",
  "icons/128x128@2x.png",
  "icons/icon.icns",
  "icons/icon.ico"
]

[dependencies]
duct = "0.13.3"
serde_json = "1.0.50"
serde_derive = "1.0.105"
serde = { version = "1.0.105", features = [ "derive" ] }
tauri = { version = "0.4", features = [ "all-api", "edge" ] }

[target."cfg(windows)".build-dependencies]
winres = "0.1"

[features]
dev-server = [ "tauri/dev-server" ]
embedded-server = [ "tauri/embedded-server" ]
no-server = [ "tauri/no-server" ]

[[bin]]
name = "stract_admin"
path = "src/main.rs"
