[workspace]

members = [
    "xtask",
]

exclude = [
  "packages/admin_core/src-tauri",
  "packages/client_core/src-tauri",
  "packages/client_tauri/src-tauri",
  "packages/new_admin_tauri/src-tauri"
]
