[package]
name = "xtask"
version = "0.1.1"
authors = ["Reidond <reidond@gmail.com>"]
edition = "2018"
publish = false

[lib]
doctest = false

[dependencies]
symlink = "0.1.0"
tokio = { version = "0.2.16", features = [ "full" ] }
clap = "2.33.0"
