[[questions]]
question = 'Lorem ipsum dolor sit amet consectetur, adipisicing elit.'
several_answers = false

[[questions.answers]]
right = false
text = '123'

[[questions.answers]]
right = true
text = '1234'

[[questions.answers]]
right = true
text = '1235'

[[questions.answers]]
right = false
text = '1236'

[[questions]]
answers = []
question = 'Lorem ipsum dolor sit amet consectetur, adipisicing elit.'
several_answers = false

[[questions]]
answers = []
question = 'Lorem ipsum dolor sit amet consectetur, adipisicing elit.'
several_answers = true

[[questions]]
answers = []
question = 'Lorem ipsum dolor sit amet consectetur, adipisicing elit.'
several_answers = false

[[questions]]
answers = []
question = 'Lorem ipsum dolor sit amet consectetur, adipisicing elit.'
several_answers = false

[[questions]]
answers = []
question = 'Lorem ipsum dolor sit amet consectetur, adipisicing elit.'
several_answers = false

[[questions]]
answers = []
question = 'Lorem ipsum dolor sit amet consectetur, adipisicing elit.'
several_answers = false

[[questions]]
answers = []
question = 'Lorem ipsum dolor sit amet consectetur, adipisicing elit.'
several_answers = false

[[questions]]
answers = []
question = 'Lorem ipsum dolor sit amet consectetur, adipisicing elit.'
several_answers = false

[[questions]]
answers = []
question = 'Lorem ipsum dolor sit amet consectetur, adipisicing elit.'
several_answers = false

[[questions]]
answers = []
question = 'Lorem ipsum dolor sit amet consectetur, adipisicing elit.'
several_answers = false
