[[data]]
question = 'Lorem ipsum dolor sit amet consectetur, adipisicing elit.'
several_answers = false

[[data.answers]]
text = '1) 123'
right = false

[[data.answers]]
text = '1) 1234'
right = false

[[data.answers]]
text = '1) 1235'
right = true

[[data.answers]]
text = '1) 1236'
right = false

[[data]]
question = 'Lorem ipsum dolor sit amet consectetur, adipisicing elit.'
several_answers = false
answers = []

[[data]]
question = 'Lorem ipsum dolor sit amet consectetur, adipisicing elit.'
several_answers = true
answers = []

[[data]]
question = 'Lorem ipsum dolor sit amet consectetur, adipisicing elit.'
several_answers = false
answers = []

[[data]]
question = 'Lorem ipsum dolor sit amet consectetur, adipisicing elit.'
several_answers = false
answers = []

[[data]]
question = 'Lorem ipsum dolor sit amet consectetur, adipisicing elit.'
several_answers = false
answers = []

[[data]]
question = 'Lorem ipsum dolor sit amet consectetur, adipisicing elit.'
several_answers = false
answers = []

[[data]]
question = 'Lorem ipsum dolor sit amet consectetur, adipisicing elit.'
several_answers = false
answers = []

[[data]]
question = 'Lorem ipsum dolor sit amet consectetur, adipisicing elit.'
several_answers = false
answers = []

[[data]]
question = 'Lorem ipsum dolor sit amet consectetur, adipisicing elit.'
several_answers = false
answers = []

[[data]]
question = 'Lorem ipsum dolor sit amet consectetur, adipisicing elit.'
several_answers = false
answers = []
