[[data]]
question = 'Lorem ipsum dolor sit amet consectetur, adipisicing elit.'
several_answers = false

[[data.answers]]
text = '123'
right = false

[[data.answers]]
text = '1234'
right = true

[[data.answers]]
text = '1235'
right = true

[[data.answers]]
text = '1236'
right = false

[[data]]
question = 'Lorem ipsum dolor sit amet consectetur, adipisicing elit.'
several_answers = false
answers = []

[[data]]
question = 'Lorem ipsum dolor sit amet consectetur, adipisicing elit.'
several_answers = true
answers = []

[[data]]
question = 'Lorem ipsum dolor sit amet consectetur, adipisicing elit.'
several_answers = false
answers = []

[[data]]
question = 'Lorem ipsum dolor sit amet consectetur, adipisicing elit.'
several_answers = false
answers = []

[[data]]
question = 'Lorem ipsum dolor sit amet consectetur, adipisicing elit.'
several_answers = false
answers = []

[[data]]
question = 'Lorem ipsum dolor sit amet consectetur, adipisicing elit.'
several_answers = false
answers = []

[[data]]
question = 'Lorem ipsum dolor sit amet consectetur, adipisicing elit.'
several_answers = false
answers = []

[[data]]
question = 'Lorem ipsum dolor sit amet consectetur, adipisicing elit.'
several_answers = false
answers = []

[[data]]
question = 'Lorem ipsum dolor sit amet consectetur, adipisicing elit.'
several_answers = false
answers = []

[[data]]
question = 'Lorem ipsum dolor sit amet consectetur, adipisicing elit.'
several_answers = false
answers = []
